// ── CampusConnect Application Data ──
// Realistic seed data for the platform

export const USERS = [
    {
        id: '1',
        name: 'Dr. Alex Johnson',
        email: 'admin@campus.edu',
        password: 'admin123',
        role: 'admin',
        department: 'Student Affairs Office',
        avatar: 'AJ',
        joinedAt: '2023-07-01',
    },
    {
        id: '2',
        name: 'Sarah Williams',
        email: 'sarah@campus.edu',
        password: 'student123',
        role: 'student',
        department: 'Computer Science',
        year: '3rd Year',
        avatar: 'SW',
        joinedAt: '2023-08-15',
        registeredActivities: ['a1', 'a3', 'a5'],
    },
    {
        id: '3',
        name: 'Mike Chen',
        email: 'mike@campus.edu',
        password: 'student123',
        role: 'student',
        department: 'Mechanical Engineering',
        year: '2nd Year',
        avatar: 'MC',
        joinedAt: '2023-08-20',
        registeredActivities: ['a2'],
    },
];

export const ACTIVITIES = [
    {
        id: 'a1',
        title: 'Web Development Club',
        description: 'Master modern web technologies — React, Node.js, TypeScript, and cloud deployments. Weekly hands-on sessions guided by industry mentors from Google and Microsoft. Build production-ready projects for your portfolio.',
        category: 'Club',
        date: '2026-03-15',
        time: '4:00 PM',
        location: 'Tech Lab A, Building 3',
        maxParticipants: 30,
        currentParticipants: 22,
        createdBy: '1',
        color: '#7c3aed',
        gradient: 'linear-gradient(135deg,#7c3aed,#4f46e5)',
        tags: ['React', 'Node.js', 'TypeScript'],
        featured: true,
    },
    {
        id: 'a2',
        title: 'Inter-College Basketball Championship',
        description: 'Annual basketball tournament featuring 12 colleges from across the region. Compete for the prestigious Golden Trophy and showcase your athletic talent in front of hundreds of spectators.',
        category: 'Sport',
        date: '2026-03-20',
        time: '9:00 AM',
        location: 'Main Sports Arena',
        maxParticipants: 50,
        currentParticipants: 38,
        createdBy: '1',
        color: '#f97316',
        gradient: 'linear-gradient(135deg,#f97316,#dc2626)',
        tags: ['Basketball', 'Championship', 'Team Sport'],
        featured: true,
    },
    {
        id: 'a3',
        title: 'TechFest 2026 — Hackathon',
        description: '48-hour innovation hackathon with prizes worth ₹5 Lakhs. Solve real industry challenges using cutting-edge technology. Open to all disciplines — coders, designers, and business students welcome!',
        category: 'Event',
        date: '2026-04-05',
        time: '10:00 AM',
        location: 'Central Auditorium',
        maxParticipants: 200,
        currentParticipants: 156,
        createdBy: '1',
        color: '#06b6d4',
        gradient: 'linear-gradient(135deg,#06b6d4,#4f46e5)',
        tags: ['Hackathon', 'Innovation', '₹5L Prize'],
        featured: true,
    },
    {
        id: 'a4',
        title: 'Photography Society',
        description: 'Explore the art of photography through weekly workshops, campus photo walks, and gallery exhibitions. Learn composition, lighting, and post-processing from professional photographers.',
        category: 'Club',
        date: '2026-03-18',
        time: '5:00 PM',
        location: 'Arts Block, Room 204',
        maxParticipants: 20,
        currentParticipants: 11,
        createdBy: '1',
        color: '#ec4899',
        gradient: 'linear-gradient(135deg,#ec4899,#7c3aed)',
        tags: ['Photography', 'Arts', 'Workshop'],
        featured: false,
    },
    {
        id: 'a5',
        title: 'Yoga & Mindfulness Workshop',
        description: 'A holistic wellness series combining yoga asanas, guided meditation, and stress-management techniques. Open to all fitness levels — beginners to advanced practitioners.',
        category: 'Event',
        date: '2026-03-22',
        time: '7:00 AM',
        location: 'Open Air Amphitheatre',
        maxParticipants: 60,
        currentParticipants: 42,
        createdBy: '1',
        color: '#10b981',
        gradient: 'linear-gradient(135deg,#10b981,#06b6d4)',
        tags: ['Yoga', 'Wellness', 'Meditation'],
        featured: false,
    },
    {
        id: 'a6',
        title: 'Campus Cricket League',
        description: 'Season-long T20 cricket league with departmental teams. Professional coaching, AI-powered performance tracking, and live commentary for every match.',
        category: 'Sport',
        date: '2026-04-10',
        time: '8:00 AM',
        location: 'Cricket Ground, South Campus',
        maxParticipants: 80,
        currentParticipants: 64,
        createdBy: '1',
        color: '#f59e0b',
        gradient: 'linear-gradient(135deg,#f59e0b,#ef4444)',
        tags: ['Cricket', 'T20', 'League'],
        featured: false,
    },
    {
        id: 'a7',
        title: 'Debate & Public Speaking Club',
        description: 'Sharpen your oratory through structured debates, Model UN simulations, and persuasive speaking workshops. Represent the college at national-level competitions.',
        category: 'Club',
        date: '2026-03-25',
        time: '3:00 PM',
        location: 'Seminar Hall B',
        maxParticipants: 25,
        currentParticipants: 15,
        createdBy: '1',
        color: '#3b82f6',
        gradient: 'linear-gradient(135deg,#3b82f6,#7c3aed)',
        tags: ['Debate', 'Leadership', 'Speaking'],
        featured: false,
    },
    {
        id: 'a8',
        title: 'Cultural Fiesta Night',
        description: 'Annual cultural extravaganza celebrating the diversity of our campus — dance, music, drama, and culinary showcases from 20+ states. The biggest event of the academic year!',
        category: 'Event',
        date: '2026-04-18',
        time: '6:00 PM',
        location: 'Main Auditorium & Ground',
        maxParticipants: 500,
        currentParticipants: 387,
        createdBy: '1',
        color: '#ec4899',
        gradient: 'linear-gradient(135deg,#ec4899,#f97316)',
        tags: ['Culture', 'Music', 'Dance'],
        featured: true,
    },
];

export const REGISTRATIONS = [
    { id: 'r1', studentId: '2', activityId: 'a1', status: 'Participated', registeredAt: '2026-01-10' },
    { id: 'r2', studentId: '2', activityId: 'a3', status: 'Registered', registeredAt: '2026-01-15' },
    { id: 'r3', studentId: '2', activityId: 'a5', status: 'Completed', registeredAt: '2026-01-20' },
    { id: 'r4', studentId: '3', activityId: 'a2', status: 'Registered', registeredAt: '2026-02-01' },
];

export const NOTIFICATIONS = [
    { id: 'n1', userId: '2', message: 'Your registration for TechFest 2026 has been confirmed! 🎉', isRead: false, createdAt: '2026-02-22T10:30:00Z', type: 'success' },
    { id: 'n2', userId: '2', message: 'Web Dev Club tomorrow at 4 PM — Topic: React Server Components', isRead: false, createdAt: '2026-02-21T08:00:00Z', type: 'info' },
    { id: 'n3', userId: '2', message: 'Congratulations! Yoga Workshop marked as Completed. 🧘', isRead: true, createdAt: '2026-02-20T18:00:00Z', type: 'success' },
    { id: 'n4', userId: '2', message: 'New activity added: Cultural Fiesta Night — Register now before spots fill!', isRead: true, createdAt: '2026-02-19T12:00:00Z', type: 'info' },
    { id: 'n5', userId: '3', message: 'Basketball Championship starts March 20. Please confirm your participation.', isRead: false, createdAt: '2026-02-22T09:00:00Z', type: 'warning' },
];
